export const SHOP_ITEMS = [
  {
    sku: "pablito",
    name: "Pablito Pintos",
    icon: "💖",
    image: "/battle/shop/pablito.webp",
    description: "Personaje premium jugable: encanto, velocidad, flash y súper de pasarela.",
    price: 3.99,
    badge: "PERSONAJE",
    category: "PREMIUM",
  },
  {
    sku: "marito",
    name: "Marito Presidencial",
    icon: "🚁",
    image: "/battle/shop/marito.webp",
    description: "Inmune a todo. Helicóptero, misiles explosivos y súper nuclear de área total.",
    price: 19.99,
    badge: "ULTRA PREMIUM",
    category: "PERSONAJE",
  },
  {
    sku: "arsenal",
    name: "Arsenal guaraní",
    icon: "💥",
    image: "/battle/shop/arsenal.webp",
    description:
      "Lanzacohetes Ka'aru, Lanzallamas Mbareté y Cañón de Itaipú, más granadas y munición.",
    price: 3.99,
    badge: "MÁS VENDIDO",
    category: "ARMAS",
  },
  {
    sku: "terere",
    name: "Tereré medicinal",
    icon: "🧉",
    image: "/battle/shop/terere.webp",
    description: "Recuperación total y una reserva extra de vida.",
    price: 3.99,
    badge: "SALVAVIDAS",
    category: "SALUD",
  },
  {
    sku: "pombero",
    name: "Ayuda del Pombero",
    icon: "🌿",
    image: "/battle/shop/pombero.webp",
    description: "Un guardián espiritual bloquea el próximo golpe decisivo.",
    price: 4.99,
    badge: "MÍSTICO",
    category: "ESPÍRITU",
  },
  {
    sku: "energia",
    name: "Energía desatada",
    icon: "⚡",
    image: "/battle/shop/energia.webp",
    description: "Más energía, súper cargado y daño aumentado durante la partida.",
    price: 3.99,
    badge: "RÁPIDO",
    category: "ENERGÍA",
  },
  {
    sku: "inmunidad",
    name: "Poder político",
    icon: "🛡️",
    image: "/battle/shop/inmunidad.webp",
    description: "Inmunidad temporal para atravesar el caos sin recibir daño.",
    price: 7.99,
    badge: "LEGENDARIO",
    category: "PODER",
  },
  {
    sku: "armadura",
    name: "Armadura de acero",
    icon: "🦾",
    image: "/battle/shop/armadura.webp",
    description: "Blindaje pesado: escudo inicial y reducción de daño en combate.",
    price: 5.99,
    badge: "TANQUE",
    category: "ARMADURA",
  },
  {
    sku: "luison",
    name: "Poder del Luizón",
    icon: "🐺",
    image: "/battle/shop/luison.webp",
    description: "Invocá un Luizón aliado que persigue enemigos y protege tu avance.",
    price: 6.99,
    badge: "PROHIBIDO",
    category: "INVOCACIÓN",
  },
  {
    sku: "avance",
    name: "Avance relámpago",
    icon: "🚀",
    image: "/battle/shop/avance.webp",
    description: "Empezá con combo, munición y ventaja para avanzar más rápido.",
    price: 4.99,
    badge: "BOOST",
    category: "PROGRESO",
  },
  {
    sku: "rivas-titulo",
    name: "Título Hernán Rivas Abogado",
    icon: "🎓",
    image: "/abogado/shop/titulo.png",
    description:
      "Título trucho de souvenir con tu nombre, marco dorado en el ring y sello HONORIS KAUSA. Humor, sin validez legal.",
    price: 3.99,
    badge: "EDICIÓN TRUCHA",
    category: "COLECCIONABLE",
    game: "abogado",
    path: "/hernan-rivas-abogado",
  },
  {
    sku: "rivas-mazo",
    name: "Mazo de la Justicia",
    icon: "🔨",
    image: "/abogado/shop/mazo.png",
    description: "Un mazo gigante: golpes lentos, daño triple y el abogado aplastado como acordeón.",
    price: 1.99,
    badge: "ORDEN EN LA SALA",
    category: "ARMA",
    game: "abogado",
    path: "/hernan-rivas-abogado",
  },
  {
    sku: "rivas-guantes",
    name: "Guantes de boxeo pro",
    icon: "🥊",
    image: "/abogado/shop/guantes.png",
    description: "Guantes rojos de campeón: más daño, combos más largos y golpe cargado más rápido.",
    price: 0.99,
    badge: "RING",
    category: "ARMA",
    game: "abogado",
    path: "/hernan-rivas-abogado",
  },
  {
    sku: "rivas-hacha",
    name: "Hacha inflable",
    icon: "🪓",
    image: "/abogado/shop/hacha.png",
    description: "Hacha de goma gigante: cada golpe hace ¡PIIIP! y lo deja rebotando como resorte.",
    price: 3.99,
    badge: "¡PIIIP!",
    category: "ARMA",
    game: "abogado",
    path: "/hernan-rivas-abogado",
  },
  {
    sku: "rivas-magnum",
    name: "Magnum de Tereré",
    icon: "🔫",
    image: "/abogado/shop/magnum.png",
    description: "Pistola de agua gigante cargada de tereré: tiros rápidos que lo dejan empapado.",
    price: 3.99,
    badge: "¡SPLASH!",
    category: "ARMA",
    game: "abogado",
    path: "/hernan-rivas-abogado",
  },
  {
    sku: "rivas-golpes-500",
    name: "Saldo · 500 golpes",
    icon: "🥊",
    image: "/abogado/shop/guantes.png",
    description:
      "500 golpes para usar cualquier arma paga sin comprarla: guantes, mazo, hacha o magnum.",
    price: 0.99,
    badge: "SALDO",
    category: "GOLPES",
    game: "abogado",
    path: "/hernan-rivas-abogado",
    credits: 500,
  },
  {
    sku: "rivas-golpes-2500",
    name: "Saldo · 2.500 golpes",
    icon: "🥊",
    image: "/abogado/shop/mazo.png",
    description: "2.500 golpes con cualquier arma paga. El pack que más rinde por partida.",
    price: 2.99,
    badge: "MÁS ELEGIDO",
    category: "GOLPES",
    game: "abogado",
    path: "/hernan-rivas-abogado",
    credits: 2500,
  },
  {
    sku: "rivas-golpes-6000",
    name: "Saldo · 6.000 golpes",
    icon: "🥊",
    image: "/abogado/shop/hacha.png",
    description: "6.000 golpes con cualquier arma paga. Para pegarle toda la semana.",
    price: 4.99,
    badge: "MEJOR PRECIO",
    category: "GOLPES",
    game: "abogado",
    path: "/hernan-rivas-abogado",
    credits: 6000,
  },
] as const;

export type ShopItem = (typeof SHOP_ITEMS)[number];
export type ShopSku = ShopItem["sku"];

type WithGame = Extract<ShopItem, { game: string }>;
/** Items sold inside Influencers Battle (the other games have their own shops). */
export const BATTLE_SHOP_ITEMS = SHOP_ITEMS.filter(
  (item): item is Exclude<ShopItem, WithGame> => !("game" in item),
);
/** Items sold inside "Hernán Rivas ES ABOGADO". */
export const ABOGADO_SHOP_ITEMS = SHOP_ITEMS.filter(
  (item): item is Extract<WithGame, { game: "abogado" }> =>
    "game" in item && item.game === "abogado",
);
export type AbogadoSku = (typeof ABOGADO_SHOP_ITEMS)[number]["sku"];

export const SHOP_SKUS = SHOP_ITEMS.map((item) => item.sku) as [ShopSku, ...ShopSku[]];
