export const SHOP_ITEMS = [
  {
    sku: "pablito",
    name: "Pablito Pintos",
    icon: "💖",
    image: "/battle/shop/pablito.webp",
    description: "Personaje premium jugable: encanto, velocidad, flash y súper de pasarela.",
    price: 3.99,
    badge: "PERSONAJE",
    category: "PREMIUM",
  },
  {
    sku: "marito",
    name: "Marito Presidencial",
    icon: "🚁",
    image: "/battle/shop/marito.webp",
    description: "Inmune a todo. Entra en helicóptero y dispara misiles de alto impacto.",
    price: 19.99,
    badge: "ULTRA PREMIUM",
    category: "PERSONAJE",
  },
  {
    sku: "arsenal",
    name: "Arsenal guaraní",
    icon: "💥",
    image: "/battle/shop/arsenal.webp",
    description: "Bazuca, granadas y hondita paraguaya para dominar una partida.",
    price: 3.99,
    badge: "MÁS VENDIDO",
    category: "ARMAS",
  },
  {
    sku: "terere",
    name: "Tereré medicinal",
    icon: "🧉",
    image: "/battle/shop/terere.webp",
    description: "Recuperación total y una reserva extra de vida.",
    price: 3.99,
    badge: "SALVAVIDAS",
    category: "SALUD",
  },
  {
    sku: "pombero",
    name: "Ayuda del Pombero",
    icon: "🌿",
    image: "/battle/shop/pombero.webp",
    description: "Un guardián espiritual bloquea el próximo golpe decisivo.",
    price: 4.99,
    badge: "MÍSTICO",
    category: "ESPÍRITU",
  },
  {
    sku: "energia",
    name: "Energía desatada",
    icon: "⚡",
    image: "/battle/shop/energia.webp",
    description: "Más energía, súper cargado y daño aumentado durante la partida.",
    price: 3.99,
    badge: "RÁPIDO",
    category: "ENERGÍA",
  },
  {
    sku: "inmunidad",
    name: "Poder político",
    icon: "🛡️",
    image: "/battle/shop/inmunidad.webp",
    description: "Inmunidad temporal para atravesar el caos sin recibir daño.",
    price: 7.99,
    badge: "LEGENDARIO",
    category: "PODER",
  },
  {
    sku: "armadura",
    name: "Armadura de acero",
    icon: "🦾",
    image: "/battle/shop/armadura.webp",
    description: "Blindaje pesado: escudo inicial y reducción de daño en combate.",
    price: 5.99,
    badge: "TANQUE",
    category: "ARMADURA",
  },
  {
    sku: "luison",
    name: "Poder del Luizón",
    icon: "🐺",
    image: "/battle/shop/luison.webp",
    description: "Invocá un Luizón aliado que persigue enemigos y protege tu avance.",
    price: 6.99,
    badge: "PROHIBIDO",
    category: "INVOCACIÓN",
  },
  {
    sku: "avance",
    name: "Avance relámpago",
    icon: "🚀",
    image: "/battle/shop/avance.webp",
    description: "Empezá con combo, munición y ventaja para avanzar más rápido.",
    price: 4.99,
    badge: "BOOST",
    category: "PROGRESO",
  },
] as const;

export type ShopItem = (typeof SHOP_ITEMS)[number];
export type ShopSku = ShopItem["sku"];

export const SHOP_SKUS = SHOP_ITEMS.map((item) => item.sku) as [ShopSku, ...ShopSku[]];
